name: .NET Core

on:
  push:
    tags: [ 'v*' ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
        
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --no-restore --verbosity normal

    #- name: Generate documentation (retrieve global tool)
    #  run: dotnet tool install xmldocmd -g

    #- name: Generate documentation (generate)
    #  run: xmldocmd Wokhan.Data.Providers/bin/Release/netcoreapp3.0/Wokhan.Data.Providers.dll docs/generated --source https://github.com/${{ github.repository }} --clean

    #- name: Generate documentation (commit)
    #  uses: EndBug/add-and-commit@v4.1.0
    #  with:
    #    add: docs
    #    message: Automated documentation update

    #Source: https://dusted.codes/github-actions-for-dotnet-core-nuget-packages#drive-nuget-version-from-git-tags
    - name: Set Nuget package version
      run: |
        arrTag=(${GITHUB_REF//\// })
        VERSION="${arrTag[2]}"
        VERSION="${VERSION//v}"
        echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Pack
      run: dotnet pack --no-build --no-restore --output Wokhan.Data.Providers/bin/Release/ --configuration Release -p:PackageVersion=${{ env.PACKAGE_VERSION }}

    - name: Publish
      run: dotnet nuget push **/bin/Release/*.nupkg --api-key ${{ secrets.nuget_apikey }} --source https://api.nuget.org/v3/index.json
